
# Website settings
title: "Megjhani"
description: "Megjhani."
keywords: "Megjhani"
baseurl: "/"
url: "http://127.0.0.1:4000"

# author
author:
  name: 'Murad'
  first_name: 'Murad'
  last_name: 'Megjhani'
  email: 'megjhani@gmail.com'
  facebook_username: 'megjhani'
  github_username: 'megjhani'
  avatar: 'static/img/landing/Murad.jpg'
  desc: 'I am a Post-doctoral Research Scientist at Columbia University Medical Center. My research interests include  applying and developing novel machine learning algorithms for neuronal data.  My current work focusses on developing sparse coding based algorithms for discovering hidden trends in the high frequency physiological data acquired from the bedside monitors at the Neuro Intesive care unit (NICU) at CUMC. My current advisor is Dr. Soojin Park.'

# localization
languages:
  - locale: 'en'
    flag: 'static/img/flags/United-States.png'

# blog img path
img_path: ''


# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
